apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "cache"
        effect: "NoSchedule"
      containers:
      - name: redis
        image: redis:7
        ports:
        - containerPort: 6379
